import type { LucideIcon } from "lucide-react";
import {
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  BadgeDollarSign,
  Coins,
  TrendingUp,
  Percent,
  Utensils,
  Coffee,
  Wine,
  Pizza,
  Apple,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Package,
  Shirt,
  Watch,
  Car,
  Bus,
  Plane,
  Train,
  Bike,
  Fuel,
  House,
  Building,
  Bed,
  Sofa,
  Lamp,
  Key,
  HeartPulse,
  Pill,
  Dumbbell,
  Activity,
  Film,
  Music,
  Gamepad2,
  BookOpen,
  Headphones,
  Tv,
  Briefcase,
  Laptop,
  Phone,
  Mail,
  Tag,
  Folder,
  Star,
  Sparkles,
  Zap,
  Repeat,
  Wifi,
  Globe,
  Map as MapIcon,
  Camera,
  Scissors,
  Wrench,
  Ellipsis,
  ArrowLeftRight,
} from "lucide-react";
import type { TransactionType } from "./types";

// Curated list of ~50 popular icons for the picker
export const ICON_PICKER_LIST = [
  // Finance
  "Wallet",
  "CreditCard",
  "Banknote",
  "PiggyBank",
  "BadgeDollarSign",
  "Coins",
  "TrendingUp",
  "Percent",
  // Food & Drink
  "Utensils",
  "Coffee",
  "Wine",
  "Pizza",
  "Apple",
  // Shopping
  "ShoppingCart",
  "ShoppingBag",
  "Gift",
  "Package",
  "Shirt",
  "Watch",
  // Transport
  "Car",
  "Bus",
  "Plane",
  "Train",
  "Bike",
  "Fuel",
  // Home & Living
  "House",
  "Building",
  "Bed",
  "Sofa",
  "Lamp",
  "Key",
  // Health & Wellness
  "HeartPulse",
  "Pill",
  "Dumbbell",
  "Activity",
  // Entertainment
  "Film",
  "Music",
  "Gamepad2",
  "BookOpen",
  "Headphones",
  "Tv",
  // Work
  "Briefcase",
  "Laptop",
  "Phone",
  "Mail",
  // Categories
  "Tag",
  "Folder",
  "Star",
  "Sparkles",
  "Zap",
  "Repeat",
  "Wifi",
  "Globe",
  "Map",
  "Camera",
  "Scissors",
  "Wrench",
  "Ellipsis",
  "ArrowLeftRight",
] as const;

// Static icon map for tree-shaking (avoids importing all Lucide icons)
export const ICON_MAP: Record<IconName, LucideIcon> = {
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  BadgeDollarSign,
  Coins,
  TrendingUp,
  Percent,
  Utensils,
  Coffee,
  Wine,
  Pizza,
  Apple,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Package,
  Shirt,
  Watch,
  Car,
  Bus,
  Plane,
  Train,
  Bike,
  Fuel,
  House,
  Building,
  Bed,
  Sofa,
  Lamp,
  Key,
  HeartPulse,
  Pill,
  Dumbbell,
  Activity,
  Film,
  Music,
  Gamepad2,
  BookOpen,
  Headphones,
  Tv,
  Briefcase,
  Laptop,
  Phone,
  Mail,
  Tag,
  Folder,
  Star,
  Sparkles,
  Zap,
  Repeat,
  Wifi,
  Globe,
  Map: MapIcon,
  Camera,
  Scissors,
  Wrench,
  Ellipsis,
  ArrowLeftRight,
};

export type IconName = (typeof ICON_PICKER_LIST)[number];

// Default icons
export const DEFAULT_ACCOUNT_ICON: IconName = "Wallet";
export const DEFAULT_CATEGORY_ICONS: Record<TransactionType, IconName> = {
  expense: "Tag",
  income: "BadgeDollarSign",
  transfer: "ArrowLeftRight",
};

// Suggested icon mapping for common category names
export const SUGGESTED_CATEGORY_ICONS: Record<string, IconName> = {
  "Food Delivery": "Utensils",
  "Dining Out": "Utensils",
  "Groceries & Home Supplies": "ShoppingCart",
  "Coffee & Snacks": "Coffee",
  Housing: "House",
  "Utilities & Connectivity": "Wifi",
  Transport: "Car",
  Subscriptions: "Repeat",
  Shopping: "ShoppingBag",
  "Entertainment & Social": "Film",
  Health: "HeartPulse",
  "Gifts & Donations": "Gift",
  "Work / Reimbursable": "Briefcase",
  Travel: "Plane",
  Salary: "BadgeDollarSign",
  Bonus: "Sparkles",
  Gift: "Gift",
  Interest: "Percent",
  Savings: "PiggyBank",
  Invest: "TrendingUp",
  "Credit Card": "CreditCard",
  Other: "Ellipsis",
};

export {
  COLOR_PALETTE,
  DEFAULT_ACCOUNT_COLOR,
  DEFAULT_CATEGORY_COLORS,
  SUGGESTED_CATEGORY_COLORS,
  type ColorValue,
} from '../theme/themeConfig';
